version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loja_teste
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rede

volumes:
  postgres-data:

networks:
  rede:
